# Generated by Django 2.2.2 on 2019-09-27 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('date_from', models.DateField(default=datetime.date.today)),
                ('date_to', models.DateField(default=datetime.date.today)),
                ('actions_budget', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('invested_money', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative')),
                ('principle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Principle')),
            ],
        ),
    ]
