# Generated by Django 2.2.2 on 2020-01-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_principles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative'),
        ),
    ]
