# Generated by Django 2.2.2 on 2020-01-29 20:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_principles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='invested_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=19, verbose_name='invested money'),
        ),
    ]
