# Generated by Django 2.2.2 on 2019-09-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_principles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Action',
        ),
    ]
