# Generated by Django 2.2.2 on 2020-02-19 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_load_principles'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='invested_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=19, verbose_name='invested hours'),
        ),
    ]
