# Generated by Django 2.2.2 on 2019-09-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190920_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
