# Generated by Django 2.2.2 on 2020-01-10 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200103_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'action'},
        ),
        migrations.AlterModelOptions(
            name='cooperative',
            options={'verbose_name': 'cooperative'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'partner'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'period'},
        ),
        migrations.AlterModelOptions(
            name='principle',
            options={'verbose_name': 'principle'},
        ),
        migrations.AddField(
            model_name='action',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative', verbose_name='cooperative'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='action',
            name='invested_money',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='invested money'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='action',
            name='partners_involved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='partners involved'),
        ),
        migrations.AlterField(
            model_name='action',
            name='principle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Principle', verbose_name='principle'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='business_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='business name'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='starting_date',
            field=models.DateField(default=datetime.date.today, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='mainprinciple',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative', verbose_name='cooperative'),
        ),
        migrations.AlterField(
            model_name='period',
            name='actions_budget',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='actions budget'),
        ),
        migrations.AlterField(
            model_name='period',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative', verbose_name='cooperative'),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='date from'),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='date to'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative', verbose_name='cooperative'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='main_principle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MainPrinciple', verbose_name='main principle'),
        ),
    ]
