# Generated by Django 2.2.2 on 2020-02-26 19:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_action_invested_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='invested_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=19, null=True, verbose_name='invested hours'),
        ),
        migrations.AlterField(
            model_name='action',
            name='invested_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=19, null=True, verbose_name='invested money'),
        ),
        migrations.AlterField(
            model_name='action',
            name='partners_involved',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='partners involved'),
        ),
    ]
