# Generated by Django 2.2.2 on 2019-12-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cooperative_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative'),
        ),
    ]
