# Generated by Django 2.2.2 on 2019-12-20 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_load_principles'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='partners_involved',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
