# Generated by Django 2.2.2 on 2020-02-28 12:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200226_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='hours_to_invest',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=19, null=True, verbose_name='hours to invest'),
        ),
    ]
