# Generated by Django 2.2.2 on 2020-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200110_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='principle',
        ),
        migrations.AddField(
            model_name='action',
            name='principles',
            field=models.ManyToManyField(to='api.Principle', verbose_name='principles'),
        ),
    ]
