# Generated by Django 2.2.2 on 2019-12-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_action_partners_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cooperative_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative'),
            preserve_default=False,
        ),
    ]
