# Generated by Django 2.2.10 on 2020-04-22 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partner_hours_to_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('name_es', models.CharField(max_length=256, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=256, null=True, verbose_name='name')),
                ('name_key', models.CharField(max_length=256)),
                ('description', models.CharField(default='', max_length=1024)),
                ('description_es', models.CharField(default='', max_length=1024, null=True)),
                ('description_en', models.CharField(default='', max_length=1024, null=True)),
                ('description_key', models.CharField(max_length=256)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='sustainable_development_goals',
            field=models.ManyToManyField(to='api.SustainableDevelopmentGoal', verbose_name='sustainable_development_goals'),
        ),
    ]
