# Generated by Django 2.2.2 on 2019-12-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_action_cooperative_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='cooperative_id',
            new_name='cooperative',
        ),
    ]
