# Generated by Django 2.2.2 on 2019-12-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_principle_cooperative_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='cooperative_id',
            new_name='cooperative',
        ),
    ]
