# Generated by Django 2.2.2 on 2019-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
