# Generated by Django 2.2.2 on 2019-12-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191228_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='cooperative_id',
            new_name='cooperative',
        ),
    ]
