# Generated by Django 2.2.2 on 2019-12-27 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191223_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative'),
        ),
        migrations.AddField(
            model_name='principle',
            name='cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cooperative'),
        ),
    ]
