# Generated by Django 2.2.2 on 2019-12-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cooperative_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
