# Generated by Django 2.2.10 on 2020-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_load_ods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='principles',
            field=models.ManyToManyField(blank=True, to='api.Principle', verbose_name='principles'),
        ),
        migrations.AlterField(
            model_name='action',
            name='sustainable_development_goals',
            field=models.ManyToManyField(blank=True, to='api.SustainableDevelopmentGoal', verbose_name='sustainable_development_goals'),
        ),
    ]
