# Generated by Django 2.2.10 on 2020-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200430_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='sustainable_development_goals_active',
            field=models.BooleanField(default=False, help_text='Designates whether this cooperative will be allowed to see and use sustainable development goals.', verbose_name='sustainable development goals active'),
        ),
    ]
