# Generated by Django 2.2.10 on 2020-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cooperative_sustainable_development_goals_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='custom_description',
            field=models.TextField(blank=True, null=True, verbose_name='custom description'),
        ),
    ]
