# Generated by Django 2.2.10 on 2020-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_principle_custom_description_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principle',
            name='custom_description',
            field=models.TextField(blank=True, default='', verbose_name='custom description'),
        ),
    ]
