# Generated by Django 2.2.20 on 2021-04-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201001_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'partner'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['date_from'], 'verbose_name': 'period'},
        ),
    ]
